// Shared 44 Department Official Icons Mapping for Web App
export const DEPT_ICON_MAP = {
  'anesthesiology & pain management': '/uploads/departments_icons/Anesthesiology_&_Pain_Management.png',
  'anesthesiology and pain management': '/uploads/departments_icons/Anesthesiology_&_Pain_Management.png',
  'anesthesiology': '/uploads/departments_icons/Anesthesiology_&_Pain_Management.png',
  'cardiology': '/uploads/departments_icons/Cardiology.png',
  'cardiothoracic surgery': '/uploads/departments_icons/Cardiothoracic_Surgery.png',
  'cardio thoracic surgery': '/uploads/departments_icons/Cardiothoracic_Surgery.png',
  'child guidance clinic': '/uploads/departments_icons/Child_Guidance_Clinic.png',
  'clinical nutrition & dietetics': '/uploads/departments_icons/Clinical_Nutrition_&_Dietetics.png',
  'clinical nutrition and dietetics': '/uploads/departments_icons/Clinical_Nutrition_&_Dietetics.png',
  'clinical nutrition': '/uploads/departments_icons/Clinical_Nutrition_&_Dietetics.png',
  'critical care & icu': '/uploads/departments_icons/Critical_Care_&_ICU.png',
  'critical care and icu': '/uploads/departments_icons/Critical_Care_&_ICU.png',
  'critical care': '/uploads/departments_icons/Critical_Care_&_ICU.png',
  'icu': '/uploads/departments_icons/Critical_Care_&_ICU.png',
  'dentistry & maxillofacial surgery': '/uploads/departments_icons/Dentistry_&_Maxillofacial_Surgery.png',
  'dentistry and maxillofacial surgery': '/uploads/departments_icons/Dentistry_&_Maxillofacial_Surgery.png',
  'dentistry': '/uploads/departments_icons/Dentistry_&_Maxillofacial_Surgery.png',
  'dental': '/uploads/departments_icons/Dentistry_&_Maxillofacial_Surgery.png',
  'dermatology': '/uploads/departments_icons/Dermatology.png',
  'ent (otolaryngology)': '/uploads/departments_icons/ENT_(Otolaryngology).png',
  'ent': '/uploads/departments_icons/ENT_(Otolaryngology).png',
  'otolaryngology': '/uploads/departments_icons/ENT_(Otolaryngology).png',
  'emergency medicine & trauma': '/uploads/departments_icons/Emergency_Medicine_&_Trauma.png',
  'emergency medicine and trauma': '/uploads/departments_icons/Emergency_Medicine_&_Trauma.png',
  'emergency medicine': '/uploads/departments_icons/Emergency_Medicine_&_Trauma.png',
  'emergency & trauma care': '/uploads/departments_icons/Emergency_Medicine_&_Trauma.png',
  'emergency': '/uploads/departments_icons/Emergency_Medicine_&_Trauma.png',
  'endocrinology': '/uploads/departments_icons/Endocrinology.png',
  'diabetology & endocrinology': '/uploads/departments_icons/Endocrinology.png',
  'diabetology and endocrinology': '/uploads/departments_icons/Endocrinology.png',
  'gastroenterology': '/uploads/departments_icons/Gastroenterology.png',
  'gastro surgery': '/uploads/departments_icons/General_Surgery.png',
  'general medicine': '/uploads/departments_icons/General_Medicine.png',
  'general surgery': '/uploads/departments_icons/General_Surgery.png',
  'geriatric medicine': '/uploads/departments_icons/Geriatric_Medicine.png',
  'gynae oncology': '/uploads/departments_icons/Gynae_Oncology.png',
  'gynecology & obstetrics': '/uploads/departments_icons/Gynecology_&_Obstetrics.png',
  'gynecology and obstetrics': '/uploads/departments_icons/Gynecology_&_Obstetrics.png',
  'gynecology': '/uploads/departments_icons/Gynecology_&_Obstetrics.png',
  'gynaecology': '/uploads/departments_icons/Gynecology_&_Obstetrics.png',
  'obstetrics': '/uploads/departments_icons/Gynecology_&_Obstetrics.png',
  'hematology': '/uploads/departments_icons/Hematology.png',
  'haematology': '/uploads/departments_icons/Hematology.png',
  'immunology & allergy': '/uploads/departments_icons/Immunology_&_Allergy.png',
  'immunology and allergy': '/uploads/departments_icons/Immunology_&_Allergy.png',
  'infectious diseases': '/uploads/departments_icons/Infectious_Diseases.png',
  'nephrology': '/uploads/departments_icons/Nephrology.png',
  'neurology': '/uploads/departments_icons/Neurology.png',
  'neuro medicine': '/uploads/departments_icons/Neurology.png',
  'neurosurgery': '/uploads/departments_icons/Neurosurgery.png',
  'neuro surgery': '/uploads/departments_icons/Neurosurgery.png',
  'nuclear medicine & pet scan': '/uploads/departments_icons/Nuclear_Medicine_&_PET_Scan.png',
  'nuclear medicine and pet scan': '/uploads/departments_icons/Nuclear_Medicine_&_PET_Scan.png',
  'nuclear medicine': '/uploads/departments_icons/Nuclear_Medicine_&_PET_Scan.png',
  'onco surgery': '/uploads/departments_icons/Onco_Surgery.png',
  'oncology & cancer care': '/uploads/departments_icons/Oncology_&_Cancer_Care.png',
  'oncology and cancer care': '/uploads/departments_icons/Oncology_&_Cancer_Care.png',
  'oncology': '/uploads/departments_icons/Oncology_&_Cancer_Care.png',
  'oncology team': '/uploads/departments_icons/Oncology_&_Cancer_Care.png',
  'ophthalmology': '/uploads/departments_icons/Ophthalmology.png',
  'orthopedics': '/uploads/departments_icons/Orthopedics.png',
  'orthopaedics': '/uploads/departments_icons/Orthopedics.png',
  'paediatric nephrology': '/uploads/departments_icons/Paediatric_Nephrology.png',
  'pediatric nephrology': '/uploads/departments_icons/Paediatric_Nephrology.png',
  'paediatric orthopaedics': '/uploads/departments_icons/Paediatric_Orthopaedics.png',
  'pediatric orthopedics': '/uploads/departments_icons/Paediatric_Orthopaedics.png',
  'pathology & laboratory medicine': '/uploads/departments_icons/Pathology_&_Laboratory_Medicine.png',
  'pathology and laboratory medicine': '/uploads/departments_icons/Pathology_&_Laboratory_Medicine.png',
  'pathology': '/uploads/departments_icons/Pathology_&_Laboratory_Medicine.png',
  'pediatric surgery': '/uploads/departments_icons/Pediatric_Surgery.png',
  'paediatric surgery': '/uploads/departments_icons/Pediatric_Surgery.png',
  'pediatrics': '/uploads/departments_icons/Pediatrics.png',
  'paediatrics': '/uploads/departments_icons/Pediatrics.png',
  'physical medicine & rehabilitation': '/uploads/departments_icons/Physical_Medicine_&_Rehabilitation.png',
  'physical medicine and rehabilitation': '/uploads/departments_icons/Physical_Medicine_&_Rehabilitation.png',
  'physical medicine': '/uploads/departments_icons/Physical_Medicine_&_Rehabilitation.png',
  'plastic & reconstructive surgery': '/uploads/departments_icons/Plastic_&_Reconstructive_Surgery.png',
  'plastic and reconstructive surgery': '/uploads/departments_icons/Plastic_&_Reconstructive_Surgery.png',
  'plastic surgery': '/uploads/departments_icons/Plastic_&_Reconstructive_Surgery.png',
  'psychiatry & mental health': '/uploads/departments_icons/Psychiatry_&_Mental_Health.png',
  'psychiatry and mental health': '/uploads/departments_icons/Psychiatry_&_Mental_Health.png',
  'psychiatry': '/uploads/departments_icons/Psychiatry_&_Mental_Health.png',
  'pulmonology': '/uploads/departments_icons/Pulmonology.png',
  'resp medicine & allergy': '/uploads/departments_icons/Pulmonology.png',
  'radiation oncology': '/uploads/departments_icons/Radiation_Oncology.png',
  'radiology & imaging': '/uploads/departments_icons/Radiology_&_Imaging.png',
  'radiology and imaging': '/uploads/departments_icons/Radiology_&_Imaging.png',
  'radiology': '/uploads/departments_icons/Radiology_&_Imaging.png',
  'reproductive medicine & ivf': '/uploads/departments_icons/Reproductive_Medicine_&_IVF.png',
  'reproductive medicine and ivf': '/uploads/departments_icons/Reproductive_Medicine_&_IVF.png',
  'reproductive medicine': '/uploads/departments_icons/Reproductive_Medicine_&_IVF.png',
  'rheumatology': '/uploads/departments_icons/Rheumatology.png',
  'thalassaemia & haemoglobinopathies': '/uploads/departments_icons/Thalassaemia_&_Haemoglobinopathies.png',
  'thalassaemia and haemoglobinopathies': '/uploads/departments_icons/Thalassaemia_&_Haemoglobinopathies.png',
  'urology': '/uploads/departments_icons/Urology.png',
  'vascular & endovascular surgery': '/uploads/departments_icons/Vascular_&_Endovascular_Surgery.png',
  'vascular and endovascular surgery': '/uploads/departments_icons/Vascular_&_Endovascular_Surgery.png'
};

export function getDeptIconUrl(deptName = '') {
  if (!deptName) return '/uploads/departments_icons/General_Medicine.png';
  const clean = deptName.toLowerCase().trim();
  return DEPT_ICON_MAP[clean] || '/uploads/departments_icons/General_Medicine.png';
}
